variables:
    IMAGEM_ORACLE: oracle/database:18.4.0-xe
    BIND_DE_PORTA: 3306:3306
    PASTA_ORIGEM_VOLUME: /D/docker/volumes/oracle/oradata
    PASTA_ORIGEM_VOLUME_SETUP: /D/docker/volumes/oracle/setup
    NOME_DA_REDE: MinhaRede
    NOME_DO_CONTAINER: MeuOracle
    CONTAINER_ATIVO: falso
    CONTAINER_EXISTE: falso

stages:
    - build
    - deploy
    - start

before_script:
    - RUNNING_CONTAINER_ID=$(docker container ls -f name=$NOME_DO_CONTAINER -f status=running -q)
    - if [[ -z $RUNNING_CONTAINER_ID ]]; then
    -   CONTAINER_ATIVO=falso;
    -   else CONTAINER_ATIVO=verdadeiro;CONTAINER_EXISTE=verdadeiro;
    - fi
    - if [[ $CONTAINER_ATIVO = "falso" ]]; then
    -   CONTAINER_ID=$(docker container ls -f name=$NOME_DO_CONTAINER -a -q)
    -   if [[ -z $CONTAINER_ID ]]; then
    -     CONTAINER_EXISTE=falso
    -     else CONTAINER_EXISTE=verdadeiro
    -   fi
    - fi

Construir_Oracle:
    stage: build
    only:
      - /^release_[0-9]+(?:.[0-9]+)+$/
    before_script:
      - IMAGE_ID=$(docker image ls --filter=reference=$IMAGEM_ORACLE -q)
      - if [[ -z $IMAGE_ID ]]; then
          IMAGEM_EXISTE=falso
      - fi
    script:
      - if [[ $IMAGEM_EXISTE = "falso" ]]; then
      -   apk update && apk add git
      -   git clone https://github.com/oracle/docker-images.git
      -   cd ./docker-images/OracleDatabase/SingleInstance/dockerfiles
      -   apk add bash
      -   bash buildContainerImage.sh -v 18.4.0 -x
      - fi

Implantacao_Oracle:
    stage: deploy
    only:
      - /^release_[0-9]+(?:.[0-9]+)+$/
    variables:
        GIT_STRATEGY: none
    script:
        - if [[ $CONTAINER_EXISTE = "falso" ]]; then
        -   docker run --name $NOME_DO_CONTAINER --network $NOME_DA_REDE -v $PASTA_ORIGEM_VOLUME:/opt/oracle/oradata -v $PASTA_ORIGEM_VOLUME_SETUP:/opt/oracle/scripts/setup -p 1521:1521 -p 5500:5500 -e ORACLE_PWD=$oraclesyspassword -e ORACLE_CHARACTERSET=AL32UTF8 -d $IMAGEM_ORACLE
        -   else echo "Container não precisa ser criado"
        - fi

Ligar_Container:
    stage: start
    except:
      - main
    variables:
        GIT_STRATEGY: none
    script:
        - if [[ -z $RUNNING_CONTAINER_ID ]]; then
        -   CONTAINER_ID=$(docker container ls -f name=$NOME_DO_CONTAINER -a -q)
        -   if [[ -z $CONTAINER_ID ]]; then
        -     CONTAINER_EXISTE=falso
        -     else CONTAINER_EXISTE=verdadeiro
        -   fi
        -   if [[ $CONTAINER_EXISTE = "verdadeiro" ]]; then
        -     docker start $NOME_DO_CONTAINER
        -     RUNNING_CONTAINER_ID=$(docker container ls -f name=$NOME_DO_CONTAINER -f status=running -q)
        -   fi
        -   else echo "Container não precisa ser iniciado"
        - fi

after_script:
    - RUNNING_CONTAINER_ID=$(docker container ls -f name=$NOME_DO_CONTAINER -f status=running -q)
    - if [[ -n $RUNNING_CONTAINER_ID ]]; then
    -   echo "Id do Container=$RUNNING_CONTAINER_ID"
    -   else "Sem container ativo"
    - fi