variables:
    APP_PATH: springbootapi
    DOCKER_TAG_NAME: $APP_PATH:latest
    NOME_DO_CONTAINER: MeuSpringBootAPI
    NOME_DA_REDE: MinhaRede
    BIND_DE_PORTA: 8080:8080

stages:
    - test
    - prebuild
    - build
    - deploy

Testes_Unitarios:
    stage: test
    artifacts:
        paths:
            - $APP_PATH/target/surefire-reports/
    cache:
        paths:
            - $APP_PATH
    image: maven:3.8.5-openjdk-17-slim
    script:
        - cd $APP_PATH
        - mvn test

Limpar_Imagem:
    stage: prebuild
    only:
      - /^release_[0-9]+(?:.[0-9]+)+$/
    dependencies: []
    cache: []
    variables:
        GIT_STRATEGY: none
    script: 
        - docker container stop $(docker container ls -a -f ancestor=$DOCKER_TAG_NAME -q) || FAILED=true
        - echo Tentativa de parada de container. Falhou? - $FAILED
        - FAILED=false
        - docker container rm $(docker container ls -a -f ancestor=$DOCKER_TAG_NAME -q) || FAILED=true
        - echo Tentativa de remoção de container. Falhou? - $FAILED 
        - FAILED=false
        - docker image rm $DOCKER_TAG_NAME || FAILED=true
        - echo Tentativa de remoção da image. Falhou? - $FAILED

Criar_Imagem:
    stage: build
    only:
      - /^release_[0-9]+(?:.[0-9]+)+$/
    dependencies: []
    cache:
        paths:
            - $APP_PATH
    variables:
        GIT_STRATEGY: none
    script:
        - docker build --no-cache -t $DOCKER_TAG_NAME ./$APP_PATH

Criar_Container:
    stage: deploy
    only:
      - /^release_[0-9]+(?:.[0-9]+)+$/
    dependencies: []
    cache: []
    variables:
        GIT_STRATEGY: none
    script:
        - docker run --name $NOME_DO_CONTAINER --network $NOME_DA_REDE -p $BIND_DE_PORTA -d $DOCKER_TAG_NAME