variables:
    APP_PATH: reactsite
    DOCKER_TAG_NAME: $APP_PATH:latest
    DOCKER_RELEASE_TAG_NAME: $APP_PATH:$CI_COMMIT_REF_NAME
    NOME_DO_CONTAINER: MeuReactSite
    NOME_DO_CONTAINER_RELEASE: MeuReactSite_$CI_COMMIT_REF_NAME
    NOME_DA_REDE: MinhaRede
    BIND_DE_PORTA: 3000:3000
    BIND_DE_PORTA_RELEASE: 3001:3000

stages:
    - prebuild
    - build
    - deploy

Limpar_Imagem_Release:
    stage: prebuild
    only:
      - /^release_[0-9]+(?:.[0-9]+)+$/
    variables:
        GIT_STRATEGY: none
    script: 
        - docker container stop $(docker container ls -a -f ancestor=$DOCKER_RELEASE_TAG_NAME -q) || FAILED=true
        - echo Tentativa de parada de container. Falhou? - $FAILED
        - FAILED=false
        - docker container rm $(docker container ls -a -f ancestor=$DOCKER_RELEASE_TAG_NAME -q) || FAILED=true
        - echo Tentativa de remoção de container. Falhou? - $FAILED 
        - FAILED=false
        - docker image rm $DOCKER_RELEASE_TAG_NAME || FAILED=true
        - echo Tentativa de remoção da image. Falhou? - $FAILED
    environment:
        name: release
        action: stop
    when: manual

Limpar_Imagem:
    stage: prebuild
    only:
      - develop
    variables:
        GIT_STRATEGY: none
    script: 
        - docker container stop $(docker container ls -a -f ancestor=$DOCKER_TAG_NAME -q) || FAILED=true
        - echo Tentativa de parada de container. Falhou? - $FAILED
        - FAILED=false
        - docker container rm $(docker container ls -a -f ancestor=$DOCKER_TAG_NAME -q) || FAILED=true
        - echo Tentativa de remoção de container. Falhou? - $FAILED 
        - FAILED=false
        - docker image rm $DOCKER_TAG_NAME || FAILED=true
        - echo Tentativa de remoção da image. Falhou? - $FAILED

Criar_Imagem_Release:
    stage: build
    only:
      - /^release_[0-9]+(?:.[0-9]+)+$/
    script:
        - docker build --no-cache -t $DOCKER_RELEASE_TAG_NAME ./$APP_PATH

Criar_Imagem:
    stage: build
    only:
      - develop
    script:
        - docker build --no-cache -t $DOCKER_TAG_NAME ./$APP_PATH

Criar_Container_Release:
    stage: deploy
    only:
      - /^release_[0-9]+(?:.[0-9]+)+$/
    variables:
        GIT_STRATEGY: none
    script:
        - docker run --name $NOME_DO_CONTAINER_RELEASE --network $NOME_DA_REDE -p $BIND_DE_PORTA_RELEASE -d $DOCKER_RELEASE_TAG_NAME
    environment:
        name: release
        on_stop: Limpar_Imagem_Release

Criar_Container:
    stage: deploy
    only:
      - develop
    variables:
        GIT_STRATEGY: none
    script:
        - docker run --name $NOME_DO_CONTAINER --network $NOME_DA_REDE -p $BIND_DE_PORTA -d $DOCKER_TAG_NAME
    environment:
        name: develop