variables:
    APP_PATH: reactsite
    DOCKER_DEVELOP_TAG_NAME: $APP_PATH:dev
    DOCKER_RELEASE_TAG_NAME: $APP_PATH:release
    NOME_DO_CONTAINER_DEVELOP: MeuReactSiteDev
    NOME_DO_CONTAINER_RELEASE: MeuReactSiteRelease
    NOME_DA_REDE: MinhaRede
    BIND_DE_PORTA_DEVELOP: 4000:3000
    BIND_DE_PORTA_RELEASE: 5000:3000

stages:
    - prebuild
    - build
    - deploy
    - clean

Limpar_Imagem_Develop:
    stage: prebuild
    only:
      - develop
    variables:
        GIT_STRATEGY: none
    script: 
        - docker container stop $(docker container ls -a -f ancestor=$DOCKER_DEVELOP_TAG_NAME -q) || FAILED=true
        - echo Tentativa de parada de container. Falhou? - $FAILED
        - FAILED=false
        - docker container rm $(docker container ls -a -f ancestor=$DOCKER_DEVELOP_TAG_NAME -q) || FAILED=true
        - echo Tentativa de remoção de container. Falhou? - $FAILED 
        - FAILED=false
        - docker image rm $DOCKER_DEVELOP_TAG_NAME || FAILED=true
        - echo Tentativa de remoção da image. Falhou? - $FAILED

Limpar_Imagem:
    stage: prebuild
    only:
      - /^release_[0-9]+(?:.[0-9]+)+$/
    variables:
        GIT_STRATEGY: none
    script: 
        - docker container stop $(docker container ls -a -f ancestor=$DOCKER_RELEASE_TAG_NAME -q) || FAILED=true
        - echo Tentativa de parada de container. Falhou? - $FAILED
        - FAILED=false
        - docker container rm $(docker container ls -a -f ancestor=$DOCKER_RELEASE_TAG_NAME -q) || FAILED=true
        - echo Tentativa de remoção de container. Falhou? - $FAILED 
        - FAILED=false
        - docker image rm $DOCKER_RELEASE_TAG_NAME || FAILED=true
        - echo Tentativa de remoção da image. Falhou? - $FAILED

Criar_Imagem_Develop:
    stage: build
    only:
      - develop
    script:
        - echo 'develop' > ./$APP_PATH/public/environment
        - docker build --no-cache -t $DOCKER_DEVELOP_TAG_NAME ./$APP_PATH

Criar_Imagem_Release:
    stage: build
    only:
      - /^release_[0-9]+(?:.[0-9]+)+$/
    script:
        - echo 'release' > ./$APP_PATH/public/environment
        - docker build --no-cache -t $DOCKER_RELEASE_TAG_NAME ./$APP_PATH

Criar_Container_Develop:
    stage: deploy
    only:
      - develop
    variables:
        GIT_STRATEGY: none
    script:
        - docker run --name $NOME_DO_CONTAINER_DEVELOP --network $NOME_DA_REDE -p $BIND_DE_PORTA_DEVELOP -d $DOCKER_DEVELOP_TAG_NAME
    environment:
        name: develop

Criar_Container_Release:
    stage: deploy
    only:
      - /^release_[0-9]+(?:.[0-9]+)+$/
    variables:
        GIT_STRATEGY: none
    script:
        - docker run --name $NOME_DO_CONTAINER_RELEASE --network $NOME_DA_REDE -p $BIND_DE_PORTA_RELEASE -d $DOCKER_RELEASE_TAG_NAME
    environment:
        name: release